export enum GetApplicationActions {
    GETAPPLICATION_DEFAULT = "GETAPPLICATION_DEFAULT",
    GETAPPLICATION_STARTED = "GETAPPLICATION_STARTED",
    GETAPPLICATION_FAILED = "GETAPPLICATION_FAILED",
    GETAPPLICATION_SUCCESSFUL = "GETAPPLICATION_SUCCESSFUL"
}

export enum AddApplicationActions {
    ADDAPPLICATION_DEFAULT = "ADDAPPLICATION_DEFAULT",
    ADDAPPLICATION_STARTED = "ADDAPPLICATION_STARTED",
    ADDAPPLICATION_FAILED = "ADDAPPLICATION_FAILED",
    ADDAPPLICATION_SUCCESSFUL = "ADDAPPLICATION_SUCCESSFUL"
}

export enum UpdateApplicationActions {
    UPDATEAPPLICATION_DEFAULT = "UPDATEAPPLICATION_DEFAULT",
    UPDATEAPPLICATION_STARTED = "UPDATEAPPLICATION_STARTED",
    UPDATEAPPLICATION_FAILED = "UPDATEAPPLICATION_FAILED",
    UPDATEAPPLICATION_SUCCESSFUL = "UPDATEAPPLICATION_SUCCESSFUL"
}

export enum DeleteApplicationActions {
    DELETEAPPLICATION_DEFAULT = "DELETEAPPLICATION_DEFAULT",
    DELETEAPPLICATION_STARTED = "DELETEAPPLICATION_STARTED",
    DELETEAPPLICATION_FAILED = "DELETEAPPLICATION_FAILED",
    DELETEAPPLICATION_SUCCESSFUL = "DELETEAPPLICATION_SUCCESSFUL"
}