export enum LoginActions {
    LOGIN_DEFAULT = "LOGIN_DEFAULT",
    LOGIN_STARTED = "LOGIN_STARTED",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
};

export enum SignupActions {
    SIGNUP_DEFAULT = "SIGNUP_DEFAULT",
    SIGNUP_STARTED = "SIGNUP_STARTED",
    SIGNUP_FAILED = "SIGNUP_FAILED",
    SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL"
}

export const LogoutAction = "LOGOUT"; 